### ISSUE TITLE
Update le template_attestation.pdf (COUVRE-FEU)

### ISSUE THREAD

**Issue by KeyKatyu** [afelipez/attestation-covid-19#1]
Salut !
Pourrais-tu update la librairie pour qu'elle soit compatible avec l'attestation du couvre feu ?
(Désormais nécessaire, depuis aujourd'hui)

Ci-joint la nouvelle attestation.
[Attestation de déplacement dérogatoire.pdf](https://github.com/afelipez/attestation-covid-19/files/5697927/Attestation.de.deplacement.derogatoire.pdf)

**Comment by KeyKatyu** [comment]
Il faut juste éditer les endroits où les champs sont écrits sur l'attestation PDF.

**Comment by afelipez** [comment]
Bonjour,
Je n'ai malheureusement pas le temps en ce moment de mettre a jour ce projet :worried:  .
Cependant si tu as envie de rajouter ces modifications toi même (tu as l'air d'avoir potasser le sujet) tu peux toujours forker le projet et le compléter.

**Comment by KeyKatyu** [comment]
Pas de soucis ! Je comprends totalement que vous soyez occupé 🙂

Je me suis posé la question du fork, comment ça marche pour la compilation/l'upload sur Jitpack ?

**Comment by KeyKatyu** [comment]
Pas de soucis ! Je comprends totalement que vous soyez occupé 🙂

Je me suis posé la question du fork, comment ça marche pour la compilation/l'upload sur Jitpack ?

**Comment by afelipez** [comment]
Concernant le fork j'imagine qu'il faut que tu créé ta propre release.
Pour le coup c'est la première fois que j'expose une librairie de manière publique et Jitpack est très simple a utiliser pour exposer ton repo : https://jitpack.io/docs/#publishing-on-jitpack.

**Comment by KeyKatyu** [comment]
D'accord merci beaucoup, bonne continuation !
Je fermes l'issue.
